services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./internal/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - prometheus

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
    ports:
      - "27017:27017"
    networks:
      - monitoring

  mongodb-exporter:
      image: 'percona/mongodb_exporter:0.40.0'
      container_name: mongodb-exporter
      environment:
        MONGODB_URI: "mongodb://exporter:exporterpass@mongo:27017/?authSource=admin"
      command: ["--collect-all", "--compatible-mode", "--discovering-mode"]
      depends_on:
        - mongo
      ports:
        - "9216:9216"
      restart: 
        unless-stopped
      networks:
        - monitoring


  license-api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
      - monitoring
    labels: { logging: "promtail" }


networks:
  monitoring:
    driver: bridge
