{
 "title": "License Api Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_sum{path!=\"/api/metrics\"}[1m])) by (path)\n/\nsum(rate(request_duration_seconds_count{path!=\"/api/metrics\"}[1m])) by (path)\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests with errors",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (path, status) (rate(requests_errors_total{path!=\"/api/metrics\"}[5m]))",
     "legendFormat": "{{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests with 200",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (path) (rate(requests_success_total{path!=\"/api/metrics\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total Requests With Path",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (rate(requests_total{path!=\"/api/metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(requests_total{path!=\"/api/metrics\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}